### ISSUE TITLE
error when use run_class_finetune_FedAvg.py

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#12]
Not using distributed mode
Load pre-trained checkpoint from: /workspace/nvidia/pradeep/SSL-FL/output/covidfl_pretrain_beit_base_central_checkpoint-999.pth
Load state_dict by model_key = model
Expand the shared relative position embedding to each transformer block. 
Traceback (most recent call last):
  File "run_class_finetune_FedAvg.py", line 500, in <module>
    main(args, model)
  File "run_class_finetune_FedAvg.py", line 295, in main
    model_all, optimizer_all, criterion_all, lr_scheduler_all, wd_scheduler_all, loss_scaler_all, mixupfn_all = Partial_Client_Selection(args, model, mode='finetune')
  File "/workspace/nvidia/pradeep/SSL-FL/code/util/FedAvg_utils.py", line 136, in Partial_Client_Selection
    print('clients_with_len: ', args.clients_with_len[proxy_single_client])
KeyError: 'train_0'

command :
python run_class_finetune_FedAvg.py --finetune /workspace/nvidia/pradeep/SSL-FL/output/covidfl_pretrain_beit_base_central_checkpoint-999.pth --output_dir /workspace/nvidia/pradeep/SSL-FL/OUTPUT_PATH_FT/ --save_ckpt --num_workers 0 --log_dir /home/SSL-FL/log_dir/

is iam missing something
pls check

**Comment by rui-yan** [comment]
Could you run your code using our released scripts? Especially please specify the number of classes using nb_classes and the dataset name. I did not see those arguments specified in your command.

**Comment by chillum-codeX** [comment]
sure
solved
Thankyou very much
