### ISSUE TITLE
How to plot metrics

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#19]
How to plot mettrics
AUROC
Recall, Precession, F1 Score, Accuracy

**Comment by rui-yan** [comment]
The generated log.txt file stores the accuracy, which can be plotted for analysis. However, if you want to evaluate other metrics, you will need to modify the `valid` function located in [FedAvg_utils](https://github.com/rui-yan/SSL-FL/blob/main/code/util/FedAvg_utils.py).

**Comment by chillum-codeX** [comment]
i have make chnages in code
getting below output
* Acc@1 89.633 loss 0.358
* AUROC: 0.976, F1-score: 0.898, Precision: 0.914, Recall: 0.889
Accuracy of the network on the 3974 validation images: 89.6%
Max accuracy: 89.63%
can i raise PR

**Comment by rui-yan** [comment]
Given that the result is based on fine-tuning for only one epoch, it looks good. However, to reproduce the result, we encourage running more epochs. 
Please refrain from raising a pull request at this time. Thx.

**Comment by chillum-codeX** [comment]
sure thanks
