### ISSUE TITLE
how to do training on custom data

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#2]
please share training from scratch

**Comment by rui-yan** [comment]
The model training commands for training from scratch can be found here: https://github.com/rui-yan/SSL-FL/blob/main/code/fed_beit/script/retina/retina_split1_scratch.sh. This is an example for training on Retina split 1 from scratch (without pre-training). You can modify the code to train on other data splits.

Please refer to SSL-FL/data to see how to train on custom data.
