### ISSUE TITLE
train or fine  tune on custom data

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#20]
Hello,
need help
i need to train on custom data
dataset was NIH chest xray dataset 
The NIH Chest X-ray Dataset was introduced in ChestX-ray8 and later ChestX-ray14 by Wang et al.[1](https://github.com/MichaelNoya/nih-chest-xray-webdataset-subset#foot1) It consists of 112,120 frontal view X-ray images of 30,805 unique patients with 14 common disease labels
https://nihcc.app.box.com/v/ChestXray-NIHCC
all_labels = ['Atelectasis', 'Cardiomegaly', 'Effusion', 'Infiltration', 'Mass', 'Nodule', 
                      'Pneumonia', 'Pneumothorax', 'Consolidation', 'Edema', 'Emphysema', 
                      'Fibrosis', 'Pleural_Thickening', 'Hernia']
                      
how should i do,unable to crack
it would be great if you edit data script or here for NIH dataset

**Comment by rui-yan** [comment]
If you want to train the model using your own custom datasets, please ensure that your data is organized according to the directory structure mentioned [here](https://github.com/rui-yan/SSL-FL/tree/main/data). 

Alternatively, you may modify the data loader in [SSL-FL/code/util/data_utils.py](https://github.com/rui-yan/SSL-FL/blob/main/code/util/data_utils.py).
