### ISSUE TITLE
unable to train ; dependency error

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#5]
actually the code was written on torch 1.7.1 and it required cuda 11.0
now i have RTX 3090 which has compute capability of sm86
so unable to train and ampere architecture needds cuda 11.3 or greater and torch 1.7.1 doesnt have cuda 11.3 support

can you please make support of pytorch 1.10 oor greater

Thanks

**Comment by rui-yan** [comment]
Please update the version of Torch accordingly based on your CUDA version.
