### ISSUE TITLE
release Fed_Skin dataset

### ISSUE THREAD

**Issue by meiluzhu** [rui-yan/SSL-FL#8]
Hi, could you release Fed_Skin dataset? thx.

**Comment by rui-yan** [comment]
Hi, we have provided the link to one federated skin dataset, which is called Derm. Please find the links under SSL-FL/data. We will provide the link to another dataset called Skin-FL soon and let you know. Thanks.

**Comment by rui-yan** [comment]
We only have the splits information for Skin_FL dataset available, which can be found [here](https://drive.google.com/file/d/1ubemzWbx_IWuE8_gx7CwAwRMyoa5vkEe/view?usp=sharing). 

To generate the Skin_FL dataset, please download the following datasets:

(1) Derm7pt from https://derm.cs.sfu.ca/Welcome.html
(2) HAM10000 from [Kaggle](https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000) 
(3) PAD-UFES from [Mendeley Data](https://data.mendeley.com/datasets/zr7vgbcyr2/1)
(4) ISIC19 using ```!wget https://s3.amazonaws.com/isic-challenge-2019/ISIC_2019_Training_Input.zip```

Once you have downloaded these datasets, please put their respective data folders under the Skin_FL folder.

**Comment by meiluzhu** [comment]
Thanks for your helpful information.
