### ISSUE TITLE
training resume

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#9]
unable to resume training 
what was the actual  processes

python run_beit_pretrain_FedAvg.py --output_dir /workspace/nvidia/pradeep/SSL-FL/output/ --num_workers 0 --log_dir /workspace/nvidia/pradeep/SSL-FL/log_dir/ --batch_size 96 --resume /workspace/nvidia/pradeep/SSL-FL/output/checkpoint-29.pth

**Comment by rui-yan** [comment]
I recommend restarting your training from the beginning and avoiding interruptions until it is completed.

**Comment by chillum-codeX** [comment]
hey rui yan
it is not possible to do continue training because of power cut issue and other issue

**Comment by rui-yan** [comment]
Why do you have power cut issue? Try to learn how to use 'tmux' for running your code to avoid this issue.

**Comment by chillum-codeX** [comment]
yes we have power cur issue
sure i will

**Comment by chillum-codeX** [comment]
parser.add_argument('--resume', default='', help='resume from checkpoint')
    parser.add_argument('--auto_resume', action='store_true')
    parser.add_argument('--no_auto_resume', action='store_false', dest='auto_resume')
    parser.set_defaults(auto_resume=True)
    
    but you set args for model training resume

**Comment by rui-yan** [comment]
I did not test for --resume functionality. Will remove these args to avoid confusion. Alternatively, you could try fix this for the code running.

**Comment by chillum-codeX** [comment]
ok
